# Generated by Django 4.1.5 on 2023-01-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMSMPAPP00', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_Shelters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Names', max_length=100)),
                ('contact', models.BigIntegerField(default='1111111111')),
                ('address', models.CharField(default='Address', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='details',
            field=models.CharField(default='Details', max_length=500),
        ),
    ]
