# Generated by Django 4.1.5 on 2023-01-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMSMPAPP00', '0002_animal_shelters_alter_feature_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Names', max_length=100)),
                ('animal_type', models.CharField(default='Animal_Types', max_length=100)),
                ('breed', models.CharField(default='Breeds', max_length=500)),
                ('age', models.CharField(default='In Months', max_length=200)),
            ],
        ),
    ]
