# Generated by Django 4.1.5 on 2023-01-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMSMPAPP00', '0003_adoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=256)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('shelter_name', models.CharField(default='Shelter Name', max_length=256)),
                ('animal_id', models.PositiveIntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedVolunteering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=256)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('shelter_name', models.CharField(default='Shelter Name', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_shelter_name', models.CharField(default='Names', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='adoption',
            name='animal_id',
            field=models.SmallIntegerField(default='0'),
        ),
    ]
