# Generated by Django 4.2.5 on 2023-09-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMSMPAPP00', '0004_appliedadoption_appliedvolunteering_volunteering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='id',
        ),
        migrations.AlterField(
            model_name='adoption',
            name='animal_id',
            field=models.PositiveIntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
